title: "🏡 The Family Newsletter"
description: A monthly digest of family life, updates, and happenings.
baseurl: "/newsletter"
url: "https://vrbabapancake.github.io"

# Build
markdown: kramdown
highlighter: rouge
permalink: /newsletters/:year/:month/:title/

# Collections
collections:
  newsletters:
    output: true
    permalink: /newsletters/:year/:month/:title/

defaults:
  - scope:
      path: ""
      type: newsletters
    values:
      layout: newsletter

plugins:
  - jekyll-feed
  - jekyll-seo-tag
